# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # Load Balancer
  config.vm.define "web-balancer" do |app|
    app.vm.hostname = "web-balancer"
    #app.vm.network "public_network"
    app.vm.network "private_network", ip: "192.168.33.10"
    app.vm.provision "shell", path: "provision/provision-for-balancer.sh"
  end

 
  # Apache HTTP Server
  config.vm.define "web-1" do |app|
    app.vm.hostname = "web-1"
    #app.vm.network "public_network"
    app.vm.network "private_network", ip: "192.168.33.11"
    app.vm.provision "shell", path: "provision/provosion_nfs_server.sh"
  end

  
  # Apache HTTP Server
  config.vm.define "web-2" do |app|
    app.vm.hostname = "web-2"
    #app.vm.network "public_network"
    app.vm.network "private_network", ip: "192.168.33.12"
    app.vm.provision "shell", path: "provision/provision_nfs_client.sh"
  end

  
  # MySQL Server
  config.vm.define "db" do |app|
    app.vm.hostname = "db"
    #app.vm.network "public_network"
    app.vm.network "private_network", ip: "192.168.33.13"
    app.vm.provision "shell", path: "provision/provision-for-mysql.sh"
  end
  

end